# Generated by Django 5.2.3 on 2025-06-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id_boleta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_reserva', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Rut_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Pnombre_cliente', models.CharField(max_length=40)),
                ('Snombre_cliente', models.CharField(max_length=40)),
                ('Papellido_cliente', models.CharField(max_length=40)),
                ('Sapellido_cliente', models.CharField(max_length=40)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.IntegerField()),
                ('direccion_cliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Rut_Empleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=40)),
                ('Papellido_Empleado', models.CharField(max_length=40)),
                ('Sapellido_Empleado', models.CharField(max_length=40)),
                ('email_Empleado', models.EmailField(max_length=254)),
                ('telefono_Empleado', models.IntegerField()),
                ('cargo', models.CharField(default='', max_length=30)),
                ('direccion', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('Rut_empresa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dv_empresa', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=40)),
                ('tipo_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('n_habitacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion_breve', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='habitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id_pago', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_Ext',
            fields=[
                ('n_s_ext', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion_breve', models.TextField(default='', max_length=100)),
                ('descripcions_ext', models.TextField(max_length=100)),
                ('precios_ext', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='servicios')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default=None)),
                ('fechaFinal', models.DateField(default=None)),
                ('precio_total', models.IntegerField(default=0)),
                ('n_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.habitacion')),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('n_s_ext', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicio_ext')),
            ],
        ),
    ]
