# Generated by Django 5.2 on 2025-05-31 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="boleta",
            fields=[
                (
                    "id_boleta",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "Rut_cliente",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Pnombre_cliente", models.CharField(max_length=40)),
                ("Snombre_cliente", models.CharField(max_length=40)),
                ("Papellido_cliente", models.CharField(max_length=40)),
                ("Sapellido_cliente", models.CharField(max_length=40)),
                ("email_cliente", models.EmailField(max_length=254)),
                ("telefono_cliente", models.IntegerField()),
                ("direccion_cliente", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ComunaModelo",
            fields=[
                (
                    "idComuna",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombreComuna", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "Rut_empresa",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("dv_empresa", models.CharField(max_length=1)),
                ("nombre", models.CharField(max_length=40)),
                ("tipo_empresa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "n_habitacion",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion", models.TextField(max_length=100)),
                ("precio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="pais",
            fields=[
                (
                    "id_pais",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("nombre_pais", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "n_s_int",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion_s_int", models.TextField(max_length=100)),
                ("precio_s_int", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Servicio_Int",
            fields=[
                (
                    "n_s_int",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion_s_int", models.TextField(max_length=100)),
                ("precio_s_int", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="pago",
            fields=[
                (
                    "id_pago",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("monto", models.IntegerField()),
                ("fecha", models.DateField()),
                (
                    "id_boleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.boleta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "Rut_Empleado",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre_empleado", models.CharField(max_length=40)),
                ("Papellido_Empleado", models.CharField(max_length=40)),
                ("Sapellido_Empleado", models.CharField(max_length=40)),
                ("email_Empleado", models.EmailField(max_length=254)),
                ("telefono_Empleado", models.IntegerField()),
                ("cargo", models.CharField(default="", max_length=10)),
                ("direccion", models.CharField(default="", max_length=60)),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.comunamodelo",
                    ),
                ),
                (
                    "id_Nacionalidad",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.pais",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reserva",
            fields=[
                (
                    "id_reserva",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "id_pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.pais"
                    ),
                ),
                (
                    "n_habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.habitacion"
                    ),
                ),
                (
                    "rut_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.cliente"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="boleta",
            name="id_reserva",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.reserva"
            ),
        ),
        migrations.CreateModel(
            name="Servicio_Ext",
            fields=[
                (
                    "n_s_ext",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcions_ext", models.TextField(max_length=100)),
                ("precios_ext", models.IntegerField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.empresa"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reserva",
            name="n_s_ext",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.servicio_ext"
            ),
        ),
    ]
