# Generated by Django 5.2 on 2025-05-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunamodelo",
            name="nombreComuna",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(default="", max_length=30),
        ),
    ]
