# Generated by Django 5.2.1 on 2025-05-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='id_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.reserva'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono_Empleado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.boleta'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pais'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='n_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.habitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='n_s_ext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicio_ext'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='n_s_int',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicio_int'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.empleado'),
        ),
    ]
