# Generated by Django 5.2 on 2025-05-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_boleta_id_reserva_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "n_s_int",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion_s_int", models.TextField(max_length=100)),
                ("precio_s_int", models.IntegerField()),
            ],
        ),
    ]
