# Generated by Django 5.2 on 2025-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_comunamodelo_nombrecomuna_alter_empleado_cargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitacion",
            name="imagen",
            field=models.ImageField(null=True, upload_to="habitaciones"),
        ),
    ]
