# Generated by Django 5.2 on 2025-05-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_servicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="n_s_int",
        ),
    ]
