# Generated by Django 5.2 on 2025-05-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_habitacion_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitacion",
            name="descripcion_breve",
            field=models.CharField(default="", max_length=100),
        ),
    ]
