# Generated by Django 5.2 on 2025-05-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_reserva_n_s_int"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="rut_empleado",
        ),
    ]
