# Generated by Django 5.2 on 2025-05-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_habitacion_descripcion_breve"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio_ext",
            name="descripcion_breve",
            field=models.TextField(default="", max_length=100),
        ),
    ]
