# Generated by Django 5.2 on 2025-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_servicio_ext_descripcion_breve"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio_ext",
            name="imagen",
            field=models.ImageField(null=True, upload_to="servicios"),
        ),
    ]
