# Generated by Django 5.2 on 2025-06-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_servicio_ext_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="hora",
        ),
        migrations.AddField(
            model_name="reserva",
            name="fechaFinal",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fechaInicio",
            field=models.DateField(default=None),
        ),
    ]
