# Generated by Django 5.2 on 2025-06-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_reserva_fecha_remove_reserva_hora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="precio_total",
            field=models.IntegerField(default=0),
        ),
    ]
