# Generated by Django 5.2 on 2025-06-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_reserva_id_reserva"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleado",
            name="comuna",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="id_Nacionalidad",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="id_pais",
        ),
        migrations.DeleteModel(
            name="Servicio",
        ),
        migrations.DeleteModel(
            name="Servicio_Int",
        ),
        migrations.DeleteModel(
            name="ComunaModelo",
        ),
        migrations.DeleteModel(
            name="pais",
        ),
    ]
