# Generated by Django 5.2 on 2025-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_empleado_comuna_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleta",
            name="id_boleta",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pago",
            name="id_pago",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
