# Generated by Django 5.2 on 2025-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_boleta_id_boleta_alter_pago_id_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="Papellido_cliente",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="Pnombre_cliente",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="Rut_cliente",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="Sapellido_cliente",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="Snombre_cliente",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion_cliente",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email_cliente",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono_cliente",
            field=models.IntegerField(max_length=9),
        ),
    ]
