# Generated by Django 5.2 on 2025-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_cliente_papellido_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono_cliente",
            field=models.IntegerField(),
        ),
    ]
