# Generated by Django 5.2 on 2025-06-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_cliente_papellido_cliente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="rut_cliente",
        ),
    ]
